/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthMonitoringSystem;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;
import java.sql.ResultSet;

/**
 *
 * @author Khian Orland
 */
public class HMS_SEARCHEMPLOYEE extends javax.swing.JFrame {

    /**
     * Creates new form HMS_SEARCHEMPLOYEE
     */
    public HMS_SEARCHEMPLOYEE() {
        try { 
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | 
            InstantiationException | 
            IllegalAccessException | 
            UnsupportedLookAndFeelException e) {System.out.println(e);
        }
        
        initComponents();
        JOptionPane.showMessageDialog(this, "Please input Employee ID for accurate search.\n"
           + "There may or may not be the same First, Middle, and Last Name.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchEmployeeTopPanel = new javax.swing.JPanel();
        searchEmployeeHeaderImageLabel = new javax.swing.JLabel();
        searchEmployeeMainPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();
        employeeFirstNameTfforSearch = new javax.swing.JTextField();
        employeeIdTf = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        employeeMiddleInitialTf = new javax.swing.JTextField();
        middleNameLabel = new javax.swing.JLabel();
        employeeLastNameTf = new javax.swing.JTextField();
        searchEmployeeButton = new javax.swing.JButton();
        sexLabel = new javax.swing.JLabel();
        bdayTf = new javax.swing.JTextField();
        sexTf = new javax.swing.JTextField();
        bdayLabel1 = new javax.swing.JLabel();
        nationalityTf = new javax.swing.JTextField();
        bdayLabel2 = new javax.swing.JLabel();
        bdayLabel3 = new javax.swing.JLabel();
        phoneNumberTf = new javax.swing.JTextField();
        civilStatusTf = new javax.swing.JTextField();
        bdayLabel4 = new javax.swing.JLabel();
        bdayLabel5 = new javax.swing.JLabel();
        bloodTypeTf = new javax.swing.JTextField();
        religionTf = new javax.swing.JTextField();
        religionLabel = new javax.swing.JLabel();
        motherEALabel = new javax.swing.JLabel();
        fatherEALabel = new javax.swing.JLabel();
        motherEATf = new javax.swing.JTextField();
        fatherEATf = new javax.swing.JTextField();
        motherEALabel1 = new javax.swing.JLabel();
        resetAllFieldsButton = new javax.swing.JButton();
        lastNameLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeAddressTf = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Employee");
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1000, 642));
        setName("searchEmployeeFrame"); // NOI18N
        setResizable(false);

        searchEmployeeTopPanel.setBackground(new java.awt.Color(235, 241, 253));

        searchEmployeeHeaderImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/HMS_TOPPANEL_SEARCHEMPLOYEE_fit.png"))); // NOI18N

        javax.swing.GroupLayout searchEmployeeTopPanelLayout = new javax.swing.GroupLayout(searchEmployeeTopPanel);
        searchEmployeeTopPanel.setLayout(searchEmployeeTopPanelLayout);
        searchEmployeeTopPanelLayout.setHorizontalGroup(
            searchEmployeeTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchEmployeeHeaderImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchEmployeeTopPanelLayout.setVerticalGroup(
            searchEmployeeTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchEmployeeTopPanelLayout.createSequentialGroup()
                .addComponent(searchEmployeeHeaderImageLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        searchEmployeeMainPanel.setBackground(new java.awt.Color(235, 241, 253));

        cancelButton.setBackground(new java.awt.Color(255, 102, 102));
        cancelButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cancelButton.setText("Cancel (Esc)");
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        firstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name:");

        employeeIdLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeeIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeIdLabel.setText("Employee ID:");

        employeeFirstNameTfforSearch.setEditable(false);
        employeeFirstNameTfforSearch.setBackground(new java.awt.Color(234, 234, 250));
        employeeFirstNameTfforSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employeeFirstNameTfforSearch.setToolTipText("First name of the Employee");
        employeeFirstNameTfforSearch.setAutoscrolls(false);
        employeeFirstNameTfforSearch.setFocusable(false);
        employeeFirstNameTfforSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeFirstNameTfforSearchActionPerformed(evt);
            }
        });
        employeeFirstNameTfforSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeFirstNameTfforSearchKeyPressed(evt);
            }
        });

        employeeIdTf.setBackground(new java.awt.Color(204, 204, 255));
        employeeIdTf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lastNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name:");

        employeeMiddleInitialTf.setEditable(false);
        employeeMiddleInitialTf.setBackground(new java.awt.Color(234, 234, 250));
        employeeMiddleInitialTf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employeeMiddleInitialTf.setToolTipText("Middle Initial or Complete Middle Name");
        employeeMiddleInitialTf.setFocusable(false);
        employeeMiddleInitialTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeMiddleInitialTfKeyPressed(evt);
            }
        });

        middleNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        middleNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        middleNameLabel.setText("Middle Name:");

        employeeLastNameTf.setEditable(false);
        employeeLastNameTf.setBackground(new java.awt.Color(234, 234, 250));
        employeeLastNameTf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employeeLastNameTf.setToolTipText("Complete Last Name");
        employeeLastNameTf.setFocusable(false);
        employeeLastNameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeLastNameTfKeyPressed(evt);
            }
        });

        searchEmployeeButton.setBackground(new java.awt.Color(153, 204, 255));
        searchEmployeeButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        searchEmployeeButton.setText("Search Employee");
        searchEmployeeButton.setBorderPainted(false);
        searchEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeButtonActionPerformed(evt);
            }
        });

        sexLabel.setBackground(new java.awt.Color(255, 255, 255));
        sexLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sexLabel.setText("Sex:");

        bdayTf.setEditable(false);
        bdayTf.setBackground(new java.awt.Color(234, 234, 250));
        bdayTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bdayTf.setFocusable(false);

        sexTf.setEditable(false);
        sexTf.setBackground(new java.awt.Color(234, 234, 250));
        sexTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sexTf.setFocusable(false);

        bdayLabel1.setBackground(new java.awt.Color(255, 255, 255));
        bdayLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bdayLabel1.setText("Birthday:");

        nationalityTf.setEditable(false);
        nationalityTf.setBackground(new java.awt.Color(234, 234, 250));
        nationalityTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nationalityTf.setFocusable(false);

        bdayLabel2.setBackground(new java.awt.Color(255, 255, 255));
        bdayLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bdayLabel2.setText("Nationality:");

        bdayLabel3.setBackground(new java.awt.Color(255, 255, 255));
        bdayLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bdayLabel3.setText("Phone Number:");

        phoneNumberTf.setEditable(false);
        phoneNumberTf.setBackground(new java.awt.Color(234, 234, 250));
        phoneNumberTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumberTf.setFocusable(false);

        civilStatusTf.setEditable(false);
        civilStatusTf.setBackground(new java.awt.Color(234, 234, 250));
        civilStatusTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        civilStatusTf.setFocusable(false);

        bdayLabel4.setBackground(new java.awt.Color(255, 255, 255));
        bdayLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bdayLabel4.setText("Civil Status:");

        bdayLabel5.setBackground(new java.awt.Color(255, 255, 255));
        bdayLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bdayLabel5.setText("Blood Type:");

        bloodTypeTf.setEditable(false);
        bloodTypeTf.setBackground(new java.awt.Color(234, 234, 250));
        bloodTypeTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bloodTypeTf.setFocusable(false);

        religionTf.setEditable(false);
        religionTf.setBackground(new java.awt.Color(234, 234, 250));
        religionTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        religionTf.setFocusable(false);

        religionLabel.setBackground(new java.awt.Color(255, 255, 255));
        religionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        religionLabel.setText("Religion:");

        motherEALabel.setBackground(new java.awt.Color(255, 255, 255));
        motherEALabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        motherEALabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        motherEALabel.setText("Image:");
        motherEALabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fatherEALabel.setBackground(new java.awt.Color(255, 255, 255));
        fatherEALabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fatherEALabel.setText("Father Email Ad.:");

        motherEATf.setEditable(false);
        motherEATf.setBackground(new java.awt.Color(234, 234, 250));
        motherEATf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        motherEATf.setFocusable(false);

        fatherEATf.setEditable(false);
        fatherEATf.setBackground(new java.awt.Color(234, 234, 250));
        fatherEATf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fatherEATf.setFocusable(false);

        motherEALabel1.setBackground(new java.awt.Color(255, 255, 255));
        motherEALabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        motherEALabel1.setText("Mother Email Ad.:");

        resetAllFieldsButton.setBackground(new java.awt.Color(234, 234, 250));
        resetAllFieldsButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        resetAllFieldsButton.setText("Clear all fields");
        resetAllFieldsButton.setToolTipText("Clear all fields after search.");
        resetAllFieldsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetAllFieldsButton.setBorderPainted(false);
        resetAllFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAllFieldsButtonActionPerformed(evt);
            }
        });

        lastNameLabel1.setBackground(new java.awt.Color(255, 255, 255));
        lastNameLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameLabel1.setText("Home Address:");

        employeeAddressTf.setEditable(false);
        employeeAddressTf.setBackground(new java.awt.Color(234, 234, 250));
        employeeAddressTf.setColumns(10);
        employeeAddressTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        employeeAddressTf.setLineWrap(true);
        employeeAddressTf.setRows(4);
        employeeAddressTf.setTabSize(5);
        employeeAddressTf.setWrapStyleWord(true);
        employeeAddressTf.setDisabledTextColor(new java.awt.Color(204, 204, 255));
        employeeAddressTf.setFocusable(false);
        jScrollPane1.setViewportView(employeeAddressTf);

        javax.swing.GroupLayout searchEmployeeMainPanelLayout = new javax.swing.GroupLayout(searchEmployeeMainPanel);
        searchEmployeeMainPanel.setLayout(searchEmployeeMainPanelLayout);
        searchEmployeeMainPanelLayout.setHorizontalGroup(
            searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(bdayLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nationalityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addComponent(bdayLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bdayLabel1)
                                    .addComponent(sexLabel))
                                .addGap(18, 18, 18)
                                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexTf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bdayTf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(bdayLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(civilStatusTf, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bdayLabel5)
                                    .addComponent(religionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(religionTf)
                                    .addComponent(bloodTypeTf))))
                        .addGap(39, 39, 39)
                        .addComponent(motherEALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fatherEALabel)
                            .addComponent(motherEALabel1))
                        .addGap(18, 18, 18)
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fatherEATf)
                            .addComponent(motherEATf, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastNameLabel1)
                    .addComponent(lastNameLabel)
                    .addComponent(firstNameLabel)
                    .addComponent(employeeIdLabel)
                    .addComponent(middleNameLabel))
                .addGap(28, 28, 28)
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addComponent(employeeIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(employeeLastNameTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeMiddleInitialTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeFirstNameTfforSearch))
                                .addGap(224, 224, 224)))
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetAllFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        searchEmployeeMainPanelLayout.setVerticalGroup(
            searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchEmployeeMainPanelLayout.createSequentialGroup()
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeFirstNameTfforSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addContainerGap(116, Short.MAX_VALUE)
                                .addComponent(employeeMiddleInitialTf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(searchEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetAllFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(religionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(religionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motherEALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdayLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchEmployeeMainPanelLayout.createSequentialGroup()
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdayTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdayLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(civilStatusTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdayLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fatherEATf)
                    .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fatherEALabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bdayLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nationalityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchEmployeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherEATf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motherEALabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdayLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchEmployeeTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchEmployeeMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchEmployeeTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchEmployeeMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void employeeFirstNameTfforSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeFirstNameTfforSearchKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeeFirstNameTfforSearchKeyPressed

    private void employeeMiddleInitialTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeMiddleInitialTfKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeeMiddleInitialTfKeyPressed

    private void employeeLastNameTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeLastNameTfKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeeLastNameTfKeyPressed

    private void searchEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmployeeButtonActionPerformed
            PreparedStatement pstmt;
            ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String username = "root";
            String password = "root";
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/health_monitoring_system_database", username, password);
            
            // employeeID search
            String employeeID_sql = "SELECT * FROM employees WHERE employeeId = ?";
            pstmt = (PreparedStatement) conn.prepareStatement(employeeID_sql);
            pstmt.setInt(1, Integer.parseInt(employeeIdTf.getText()));
            
            rs = pstmt.executeQuery();
            if (rs.next())
            {
                employeeFirstNameTfforSearch.setText(rs.getString("firstName"));
                employeeMiddleInitialTf.setText(rs.getString("middleInitial"));
                employeeLastNameTf.setText(rs.getString("lastName"));
                employeeAddressTf.setText(rs.getString("employeeAddress"));
                sexTf.setText(rs.getString("employeeGender"));
                bdayTf.setText(rs.getString("dateOfBirth"));
                nationalityTf.setText(rs.getString("employeeNationality"));
                phoneNumberTf.setText(rs.getString("cellphoneNumber"));
                religionTf.setText(rs.getString("employeeReligion"));
                bloodTypeTf.setText(rs.getString("employeeBloodType"));
                civilStatusTf.setText(rs.getString("civilStatus"));
                fatherEATf.setText(rs.getString("fatherEmailAddress"));
                motherEATf.setText(rs.getString("motherEmailAddress"));
                
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Employee ID "+ employeeIdTf.getText() + " is not found in the System.");
            }
            conn.close();
        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Please Employee ID to Search.");
        }
 
    }//GEN-LAST:event_searchEmployeeButtonActionPerformed

    private void resetAllFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAllFieldsButtonActionPerformed
        employeeIdTf.setText("");
        employeeFirstNameTfforSearch.setText("");
        employeeMiddleInitialTf.setText("");
        employeeLastNameTf.setText("");
        employeeAddressTf.setText("");
        sexTf.setText("");
        bdayTf.setText("");
        phoneNumberTf.setText("");
        nationalityTf.setText("");
        fatherEATf.setText("");
        motherEATf.setText("");
        religionTf.setText("");
        bloodTypeTf.setText("");
        civilStatusTf.setText("");

        this.repaint();
    }//GEN-LAST:event_resetAllFieldsButtonActionPerformed

    private void employeeFirstNameTfforSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeFirstNameTfforSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeFirstNameTfforSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMS_SEARCHEMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HMS_SEARCHEMPLOYEE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bdayLabel1;
    public javax.swing.JLabel bdayLabel2;
    public javax.swing.JLabel bdayLabel3;
    public javax.swing.JLabel bdayLabel4;
    public javax.swing.JLabel bdayLabel5;
    private javax.swing.JTextField bdayTf;
    private javax.swing.JTextField bloodTypeTf;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField civilStatusTf;
    private javax.swing.JTextArea employeeAddressTf;
    private javax.swing.JTextField employeeFirstNameTfforSearch;
    public javax.swing.JLabel employeeIdLabel;
    private javax.swing.JTextField employeeIdTf;
    private javax.swing.JTextField employeeLastNameTf;
    private javax.swing.JTextField employeeMiddleInitialTf;
    public javax.swing.JLabel fatherEALabel;
    private javax.swing.JTextField fatherEATf;
    public javax.swing.JLabel firstNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lastNameLabel;
    public javax.swing.JLabel lastNameLabel1;
    public javax.swing.JLabel middleNameLabel;
    public javax.swing.JLabel motherEALabel;
    public javax.swing.JLabel motherEALabel1;
    private javax.swing.JTextField motherEATf;
    private javax.swing.JTextField nationalityTf;
    private javax.swing.JTextField phoneNumberTf;
    public javax.swing.JLabel religionLabel;
    private javax.swing.JTextField religionTf;
    private javax.swing.JButton resetAllFieldsButton;
    private javax.swing.JButton searchEmployeeButton;
    private javax.swing.JLabel searchEmployeeHeaderImageLabel;
    private javax.swing.JPanel searchEmployeeMainPanel;
    private javax.swing.JPanel searchEmployeeTopPanel;
    public javax.swing.JLabel sexLabel;
    private javax.swing.JTextField sexTf;
    // End of variables declaration//GEN-END:variables
}
