package healthMonitoringSystem;

import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author khian
 */
public class HMS_PATIENT_MANAGEMENTSYSTEM extends javax.swing.JFrame {

    HMS_DATABASECONNECTION dbConnect = new HMS_DATABASECONNECTION();
    //get Strings of 'em all
    String patientIdString = "";
    String firstName = "";
    String middleName = "";
    String lastName = "";
    String genderSelect = "";
    String dateOfBirth = "";
    String bloodType = "";
    String civilStatus = "";
    String religion = "";
    String nationality = "";
    String cellphoneNumber = "";
    String image_path = null;
    Connection connx;
    static DefaultTableModel model;
    int currentPosition = 0;
    HMS_DATAACESSOBJECT_IMPLEMENTATION dao = new HMS_DATAACESSOBJECT_IMPLEMENTATION();

    /**
     * Creates new form HMS_PATIENT_MANAGEMENTSYSTEM
     */
    public HMS_PATIENT_MANAGEMENTSYSTEM() throws Exception {
        initComponents();
        connx = dbConnect.databaseConnection();
        // Populating patientDataTable
        dao.populatepatientDataTableFromMySQLDatabase(model, patientDataTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        patientFullMainPanel = new javax.swing.JPanel();
        patientIDLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        bloodTypeLabel = new javax.swing.JLabel();
        cellphoneNumberLabel = new javax.swing.JLabel();
        civilStatusLabel = new javax.swing.JLabel();
        religionLabel = new javax.swing.JLabel();
        nationalityLabel = new javax.swing.JLabel();
        imagePathLabel = new javax.swing.JLabel();
        patientIdTf = new javax.swing.JTextField();
        firstNameTf = new javax.swing.JTextField();
        middleNameTf = new javax.swing.JTextField();
        lastNameTf = new javax.swing.JTextField();
        dateOfBirthPicker = new com.github.lgooddatepicker.components.DatePicker();
        maleCbButton = new javax.swing.JCheckBox();
        femaleCbButton = new javax.swing.JCheckBox();
        bloodTypeCB = new javax.swing.JComboBox<>();
        civilStatusCB = new javax.swing.JComboBox<>();
        religionCB = new javax.swing.JComboBox<>();
        nationalityTf = new javax.swing.JTextField();
        phoneNumberTf = new javax.swing.JTextField();
        imagePathTf = new javax.swing.JTextField();
        labelImage = new javax.swing.JLabel();
        browseImageButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        moveRowUpButton = new javax.swing.JButton();
        moveRowDownButton = new javax.swing.JButton();
        listSelectedButton = new javax.swing.JButton();
        exportExcelButton = new javax.swing.JButton();
        importExcelButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientDataTable = new javax.swing.JTable();
        imageNameLabel = new javax.swing.JLabel();
        imageNameTf = new javax.swing.JTextField();
        firstItemInListButton = new javax.swing.JButton();
        lastItemInListButton = new javax.swing.JButton();
        nextItemInListButton = new javax.swing.JButton();
        previousItemInListButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filterSearchTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MHMS Patient Data Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setName("patientMainFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        patientFullMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        patientFullMainPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        patientFullMainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        patientIDLabel.setText("Patient ID:");
        patientIDLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        firstNameLabel.setText("First Name:");
        firstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        middleNameLabel.setText("Middle Name:");
        middleNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lastNameLabel.setText("Last Name:");
        lastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        genderLabel.setText("Sex:");
        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        dateOfBirthLabel.setText("Date of Birth:");
        dateOfBirthLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        bloodTypeLabel.setText("Blood Type:");
        bloodTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        cellphoneNumberLabel.setText("Cellphone Num. :");
        cellphoneNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        civilStatusLabel.setText("Civil Status:");
        civilStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        religionLabel.setText("Religion:");
        religionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        nationalityLabel.setText("Nationality:");
        nationalityLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        imagePathLabel.setText("Image Path:");
        imagePathLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        patientIdTf.setEnabled(false);

        firstNameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTfKeyTyped(evt);
            }
        });

        middleNameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                middleNameTfKeyTyped(evt);
            }
        });

        lastNameTf.setMaximumSize(new java.awt.Dimension(7, 20));
        lastNameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameTfKeyTyped(evt);
            }
        });

        dateOfBirthPicker.setBackground(new java.awt.Color(255, 255, 255));
        dateOfBirthPicker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        genderGroup.add(maleCbButton);
        maleCbButton.setText("Male");
        maleCbButton.setBackground(new java.awt.Color(255, 255, 255));
        maleCbButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        genderGroup.add(femaleCbButton);
        femaleCbButton.setText("Female");
        femaleCbButton.setBackground(new java.awt.Color(255, 255, 255));
        femaleCbButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bloodTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unspecified", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        bloodTypeCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        civilStatusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unspecified", "Single", "Married", "Divorced", "Widowed" }));
        civilStatusCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        religionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aglipayan", "Buddhism", "Catholic", "Hinduism", "Iglesia ni Cristo", "Islam", "Judaism", "Non-Roman Catholic and Protestant", "Seventh-day Adventist", "Unspecified", " " }));
        religionCB.setSelectedIndex(9);
        religionCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nationalityTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nationalityTfKeyTyped(evt);
            }
        });

        phoneNumberTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumberTf.setMaximumSize(new java.awt.Dimension(7, 20));
        phoneNumberTf.setPreferredSize(new java.awt.Dimension(7, 20));
        phoneNumberTf.setToolTipText("Please indicate your Phone number starting at 09xxxxxxxx");
        phoneNumberTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberTfKeyTyped(evt);
            }
        });
        phoneNumberTf.setDocument(new JTextFieldLimit(11));

        imagePathTf.setEditable(false);
        imagePathTf.setBorder(null);
        imagePathTf.setEnabled(false);
        imagePathTf.setFocusable(false);

        labelImage.setBackground(new java.awt.Color(102, 102, 102));
        labelImage.setOpaque(true);

        browseImageButton.setText("Browse Image");
        browseImageButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        browseImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImageButtonActionPerformed(evt);
            }
        });

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/addIcon.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setBackground(new java.awt.Color(235, 245, 255));
        addButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/refreshIcon.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.setBackground(new java.awt.Color(235, 245, 255));
        updateButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        updateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/deleteIcon.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBackground(new java.awt.Color(235, 245, 255));
        deleteButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/clearIcon.png"))); // NOI18N
        clearButton.setText("Clear");
        clearButton.setBackground(new java.awt.Color(235, 245, 255));
        clearButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        clearButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        moveRowUpButton.setText("Move Row Up");
        moveRowUpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        moveRowUpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        moveRowUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRowUpButtonActionPerformed(evt);
            }
        });

        moveRowDownButton.setText("Move Row Down");
        moveRowDownButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        moveRowDownButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        moveRowDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRowDownButtonActionPerformed(evt);
            }
        });

        listSelectedButton.setText("List Selected");
        listSelectedButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listSelectedButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        listSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSelectedButtonActionPerformed(evt);
            }
        });

        exportExcelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/excel.png"))); // NOI18N
        exportExcelButton.setText("Export (Excel)");
        exportExcelButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exportExcelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        exportExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelButtonActionPerformed(evt);
            }
        });

        importExcelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/excel.png"))); // NOI18N
        importExcelButton.setText("Import (Excel)");
        importExcelButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        importExcelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        importExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importExcelButtonActionPerformed(evt);
            }
        });

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/printerIcon.png"))); // NOI18N
        printButton.setText("Print Entire Patient Database");
        printButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        patientDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Middle Name", "Last Name", "Gender", "Birthday", "Blood Type", "Civil Status", "Religion", "Nationality", "Cellphone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientDataTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patientDataTable.setGridColor(new java.awt.Color(204, 204, 255));
        patientDataTable.setMaximumSize(new java.awt.Dimension(800, 0));
        patientDataTable.setMinimumSize(new java.awt.Dimension(800, 0));
        patientDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientDataTableMouseClicked(evt);
            }
        });
        patientDataTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patientDataTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(patientDataTable);
        if (patientDataTable.getColumnModel().getColumnCount() > 0) {
            patientDataTable.getColumnModel().getColumn(0).setMaxWidth(50);
            patientDataTable.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        imageNameLabel.setText("Image Name:");
        imageNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        imageNameTf.setEditable(false);
        imageNameTf.setBorder(null);
        imageNameTf.setEnabled(false);
        imageNameTf.setFocusable(false);

        firstItemInListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/first.png"))); // NOI18N
        firstItemInListButton.setText("First");
        firstItemInListButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstItemInListButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        firstItemInListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstItemInListButtonActionPerformed(evt);
            }
        });

        lastItemInListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/last.png"))); // NOI18N
        lastItemInListButton.setText("Last");
        lastItemInListButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastItemInListButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        lastItemInListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastItemInListButtonActionPerformed(evt);
            }
        });

        nextItemInListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/next.png"))); // NOI18N
        nextItemInListButton.setText("Next");
        nextItemInListButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextItemInListButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        nextItemInListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextItemInListButtonActionPerformed(evt);
            }
        });

        previousItemInListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/mainprogram/previous.png"))); // NOI18N
        previousItemInListButton.setText("Previous");
        previousItemInListButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        previousItemInListButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        previousItemInListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousItemInListButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(235, 241, 253));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Filter Search:");

        filterSearchTf.setBackground(new java.awt.Color(204, 204, 255));
        filterSearchTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filterSearchTf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        filterSearchTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterSearchTfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout patientFullMainPanelLayout = new javax.swing.GroupLayout(patientFullMainPanel);
        patientFullMainPanel.setLayout(patientFullMainPanelLayout);
        patientFullMainPanelLayout.setHorizontalGroup(
            patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(firstNameLabel)
                                                    .addComponent(patientIDLabel)
                                                    .addComponent(middleNameLabel)
                                                    .addComponent(dateOfBirthLabel)
                                                    .addComponent(bloodTypeLabel)
                                                    .addComponent(civilStatusLabel)
                                                    .addComponent(religionLabel)
                                                    .addComponent(nationalityLabel)
                                                    .addComponent(cellphoneNumberLabel)
                                                    .addComponent(lastNameLabel))
                                                .addGap(19, 19, 19))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, patientFullMainPanelLayout.createSequentialGroup()
                                                .addComponent(genderLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(middleNameTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNameTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                                .addComponent(maleCbButton)
                                                .addGap(29, 29, 29)
                                                .addComponent(femaleCbButton))
                                            .addComponent(dateOfBirthPicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bloodTypeCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nationalityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(religionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(civilStatusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(patientIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imagePathLabel)
                                            .addComponent(imageNameLabel))
                                        .addGap(68, 68, 68)
                                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imagePathTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(imageNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(browseImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientFullMainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(82, 82, 82)
                                .addComponent(filterSearchTf)))
                        .addGap(86, 86, 86)
                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, patientFullMainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(listSelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moveRowUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moveRowDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                        .addComponent(firstItemInListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastItemInListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(importExcelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(exportExcelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientFullMainPanelLayout.createSequentialGroup()
                                        .addComponent(previousItemInListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nextItemInListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1865, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        patientFullMainPanelLayout.setVerticalGroup(
            patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientFullMainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(printButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(exportExcelButton)
                                    .addComponent(importExcelButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstItemInListButton)
                                    .addComponent(lastItemInListButton)
                                    .addComponent(previousItemInListButton)
                                    .addComponent(nextItemInListButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listSelectedButton)
                            .addComponent(moveRowUpButton)
                            .addComponent(moveRowDownButton)
                            .addComponent(filterSearchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(patientIDLabel)
                                    .addComponent(patientIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNameLabel)
                                    .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(middleNameLabel)
                                    .addComponent(middleNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameLabel)
                                    .addComponent(lastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genderLabel)
                                    .addComponent(maleCbButton)
                                    .addComponent(femaleCbButton))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dateOfBirthLabel)
                                    .addComponent(dateOfBirthPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bloodTypeLabel)
                                    .addComponent(bloodTypeCB))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(civilStatusLabel)
                                    .addComponent(civilStatusCB))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(religionLabel)
                                    .addComponent(religionCB))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nationalityLabel)
                                    .addComponent(nationalityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cellphoneNumberLabel)
                                    .addComponent(phoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(patientFullMainPanelLayout.createSequentialGroup()
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imagePathTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagePathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(patientFullMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imageNameLabel)
                                    .addComponent(imageNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(browseImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(patientFullMainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectPatient(int counter) {
        patientIdTf.setText(Integer.toString(dao.patientList().get(counter).getID()));
        firstNameTf.setText(dao.patientList().get(counter).getfirstName());
        middleNameTf.setText(dao.patientList().get(counter).getMiddleName());
        lastNameTf.setText(dao.patientList().get(counter).getLastName());
        String gender = dao.patientList().get(counter).getGender();
        if (gender.equals("Male")) {
            maleCbButton.setSelected(true);
        } else if (gender.contains("Female")) {
            femaleCbButton.setSelected(true);
        }
        String bloodTypeString = dao.patientList().get(counter).getbloodType();
        for (int row = 0; row < bloodTypeCB.getItemCount(); row++) {
            if (bloodTypeCB.getItemAt(row).equalsIgnoreCase(bloodTypeString)) {
                bloodTypeCB.setSelectedIndex(row);
            }
        }
        String civilStatusString = dao.patientList().get(counter).getcivilStatus();
        for (int row = 0; row < civilStatusCB.getItemCount(); row++) {
            if (civilStatusCB.getItemAt(row).equalsIgnoreCase(civilStatusString)) {
                civilStatusCB.setSelectedIndex(row);
            }
        }
        String religionString = dao.patientList().get(counter).getReligion();
        for (int row = 0; row < religionCB.getItemCount(); row++) {
            if (religionCB.getItemAt(row).equalsIgnoreCase(religionString)) {
                religionCB.setSelectedIndex(row);
            }
        }
        nationalityTf.setText(dao.patientList().get(counter).getNationality());
        phoneNumberTf.setText(dao.patientList().get(counter).getphoneNumber());

        try {
            labelImage.setIcon(new ImageIcon(new ImageIcon(dao.patientList().get(counter).getimagePath()).getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_SMOOTH)));
        } catch (Exception err) {
            this.invalidate();
            this.validate();
            this.repaint();
        } finally {
            labelImage.setIcon(new ImageIcon(new ImageIcon(dao.patientList().get(counter).getimagePath()).getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_SMOOTH)));
        }
    }
    // limit phone number max

    // FILTER DATA
    private void filter(String query) {
        DefaultTableModel dm = (DefaultTableModel) patientDataTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        patientDataTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    public class JTextFieldLimit extends PlainDocument {

        private final int limit;

        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
            if (str == null) {
                return;
            }

            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }
    private void phoneNumberTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberTfKeyTyped
        // allow only numbers
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberTfKeyTyped

    private void browseImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImageButtonActionPerformed
        // Default image location

        String currentDirectoryPath = "C:\\Users\\Public\\Pictures\\";
        JFileChooser imageFileChooser = new JFileChooser(currentDirectoryPath);
        int imageChooser = imageFileChooser.showOpenDialog(null);
        imageFileChooser.setDialogTitle("Chose Image...");
        //Only choose "png", "jpg", "jpeg" files
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        imageFileChooser.setFileFilter(fnef);

        if (imageChooser == JFileChooser.APPROVE_OPTION) {
            File imageFile = imageFileChooser.getSelectedFile();
            String imageFileName = imageFile.getName();
            String imageFilePath = imageFile.getAbsolutePath();
            imageNameTf.setText(imageFileName); // display image name in the textfield

            ImageIcon imageIcon = new ImageIcon(imageFilePath);
            // resize image to fill LabelImage
            Image image = imageIcon.getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_SMOOTH);
            // Display Image on LabelImage
            ImageIcon resizedImagedIcon = new ImageIcon(image);
            labelImage.setIcon(resizedImagedIcon);
            // Display Image Path in imagePathTf
            imagePathTf.setText(imageFilePath);
            image_path = imageFilePath;
        }

    }//GEN-LAST:event_browseImageButtonActionPerformed
    public boolean verifyFields() throws ParseException {
        String firstNameString = firstNameTf.getText();
        String middleNameString = middleNameTf.getText();
        String lastNameString = lastNameTf.getText();
        String selectedbDay = dateOfBirthPicker.getText();
        String nationalityString = nationalityTf.getText();
        // Check empty fields
        if (firstNameString.trim().equals("") || middleNameString.trim().equals("")
                || lastNameString.trim().equals("") || selectedbDay.trim().equals("")
                || nationalityString.equals("")) {
            JOptionPane.showMessageDialog(null, "One or more fields are empty.\nPlease fill-up all forms.", "Empty fields", JOptionPane.INFORMATION_MESSAGE);
            this.repaint();
            return false;
        } // If everything is okay...
        else {
            return true;
        }
    }
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (image_path == null) {
            JOptionPane.showMessageDialog(null, "It is recommended to have an image of the patient to verify identity.", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                firstName = firstNameTf.getText();
                middleName = middleNameTf.getText();
                lastName = lastNameTf.getText();

                if (maleCbButton.isSelected()) {
                    genderSelect = "Male";
                } else if (femaleCbButton.isSelected()) {
                    genderSelect = "Female";
                }

                dateOfBirth = dateOfBirthPicker.getDateStringOrEmptyString(); // bday
                bloodType = String.valueOf(bloodTypeCB.getSelectedItem());
                civilStatus = String.valueOf(civilStatusCB.getSelectedItem());
                religion = String.valueOf(religionCB.getSelectedItem());
                nationality = nationalityTf.getText();
                cellphoneNumber = phoneNumberTf.getText();

                if (verifyFields()) {
                    PreparedStatement pst;
                    String registerPatientQuery = "INSERT INTO `patients`(`FirstName`, `MiddleName`, `LastName`, `Gender`, `DateOfBirth`, `BloodType`, `CivilStatus`, `Religion`, `Nationality`, `CellphoneNumber`, `ImagePath`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";

                    try {

                        pst = (PreparedStatement) HEALTH_MONITORING_SYSTEM_DATABASE.getConnection().prepareStatement(registerPatientQuery);
                        pst.setString(1, firstName);
                        pst.setString(2, middleName);
                        pst.setString(3, lastName);
                        pst.setString(4, genderSelect);
                        pst.setString(5, dateOfBirth);
                        pst.setString(6, bloodType);
                        pst.setString(7, civilStatus);
                        pst.setString(8, religion);
                        pst.setString(9, nationality);
                        pst.setString(10, cellphoneNumber);

                        try {
                            // Save the image as BLOB in the Database
                            if (image_path != null) {

                                InputStream image = new FileInputStream(new File(image_path));
                                pst.setBlob(11, image);
                            } else if (image_path == null) {
                                pst.setNull(11, java.sql.Types.NULL);
                                System.out.println("No image attached.");
                            } else {
                                pst.setNull(1, java.sql.Types.NULL);
                                System.out.println("No image attached.");
                            }
                            if (pst.executeUpdate() != 0) {
                                JOptionPane.showMessageDialog(null, "Patient data added.");
                                clearAllInputFields();
                                // Refresh patientDataTable after adding new entry to database
                                dao.populatepatientDataTableFromMySQLDatabase(model, patientDataTable);

                                this.invalidate();
                                this.validate();
                                this.repaint();
                            } else {
                                JOptionPane.showMessageDialog(null, "Error: Check your Information.");
                            }
                            pst.setNull(11, java.sql.Types.NULL);
                        } catch (FileNotFoundException ex) {
                            JOptionPane.showMessageDialog(null, ex);
                        }
                    } catch (HeadlessException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }

                }
            } catch (ParseException ex) {
                Logger.getLogger(HMS_PATIENT_MANAGEMENTSYSTEM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void nationalityTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalityTfKeyTyped
        char charInputOnly = evt.getKeyChar();
        if (!(Character.isAlphabetic(charInputOnly) || (charInputOnly == KeyEvent.VK_BACK_SPACE) || charInputOnly == KeyEvent.VK_DELETE || charInputOnly == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_nationalityTfKeyTyped

    private void firstNameTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTfKeyTyped
        char charInputOnly = evt.getKeyChar();
        if (!(Character.isAlphabetic(charInputOnly) || (charInputOnly == KeyEvent.VK_BACK_SPACE) || charInputOnly == KeyEvent.VK_DELETE || charInputOnly == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_firstNameTfKeyTyped

    private void middleNameTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_middleNameTfKeyTyped
        char charInputOnly = evt.getKeyChar();
        if (!(Character.isAlphabetic(charInputOnly) || (charInputOnly == KeyEvent.VK_BACK_SPACE) || charInputOnly == KeyEvent.VK_DELETE || charInputOnly == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_middleNameTfKeyTyped

    private void lastNameTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTfKeyTyped
        char charInputOnly = evt.getKeyChar();
        if (!(Character.isAlphabetic(charInputOnly) || (charInputOnly == KeyEvent.VK_BACK_SPACE) || charInputOnly == KeyEvent.VK_DELETE || charInputOnly == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_lastNameTfKeyTyped
    private void clearAllInputFields() {
        patientIdTf.setText("");
        firstNameTf.setText("");
        middleNameTf.setText("");
        lastNameTf.setText("");
        genderGroup.clearSelection();
        bloodTypeCB.setSelectedIndex(0);
        civilStatusCB.setSelectedIndex(0);
        religionCB.setSelectedIndex(9);
        nationalityTf.setText("");
        phoneNumberTf.setText("");
        labelImage.setIcon(null);
        image_path = null;
        imagePathTf.setText("");
        imageNameTf.setText("");

    }
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearAllInputFields();
        this.invalidate();
        this.validate();
        this.repaint();
    }//GEN-LAST:event_clearButtonActionPerformed

    int patientDataTableSelectedRow;
    private void patientDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientDataTableMouseClicked
        patientDataTableSelectedRow = patientDataTable.getSelectedRow();

        // make currentPosition start counting from the selected JTable Row
        currentPosition = patientDataTableSelectedRow;
        selectPatient(patientDataTableSelectedRow);
    }//GEN-LAST:event_patientDataTableMouseClicked

    private void firstItemInListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstItemInListButtonActionPerformed
        currentPosition = 0;
        selectPatient(currentPosition);
    }//GEN-LAST:event_firstItemInListButtonActionPerformed

    private void lastItemInListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastItemInListButtonActionPerformed
        currentPosition = dao.patientList().size() - 1;
        selectPatient(currentPosition);
    }//GEN-LAST:event_lastItemInListButtonActionPerformed

    private void nextItemInListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextItemInListButtonActionPerformed
        // Increment currentPosition to display  next item on input fields

        currentPosition++;

        if (currentPosition > dao.patientList().size() - 1) {
            currentPosition = 0;
        }

        // If you reach the last item , move back to the first item.
        selectPatient(currentPosition);
    }//GEN-LAST:event_nextItemInListButtonActionPerformed

    private void previousItemInListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousItemInListButtonActionPerformed
        // Decrenebt currentPosition to access/view previous item in a list

        currentPosition--;
        if (currentPosition < 0) {
            currentPosition = dao.patientList().size() - 1;
        }
        selectPatient(currentPosition);
    }//GEN-LAST:event_previousItemInListButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        // first check if the ID field is Empty.)
        if (patientIdTf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Field is Empty.");
        } else {

            // Delete data from MySQL Database
            Connection dbconnection = null;
            PreparedStatement pst = null;
            String deleteSQLQuery = "DELETE FROM `patients` WHERE id = ?";

            try {
                dbconnection = this.connx;
                pst = (PreparedStatement) dbconnection.prepareStatement(deleteSQLQuery);
                pst.setInt(1, Integer.parseInt(patientIdTf.getText()));
                int deleteSTMT = pst.executeUpdate();

                if (deleteSTMT > 0) {
                    JOptionPane.showMessageDialog(null, "Deleted Data Successfully!");
                    // Close inpt fields after deleting  
                    clearAllInputFields();
                    // Refresh JTable to remove deleted row
                    dao.populatepatientDataTableFromMySQLDatabase(model, patientDataTable);
                    this.invalidate();
                    this.validate();
                    this.repaint();

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } finally {
                // Close Connection
                try {
                    if (pst != null) {
                        pst.close();
                    }
//                    if (dbconnection != null) {
//                        dbconnection.close();
//                    }
                } catch (SQLException sQLException) {
                    sQLException.getMessage();
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (patientIdTf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Field is Empty.");
        } else {

            if (labelImage == null) {
                JOptionPane.showMessageDialog(null, "It is recommended to have an image of the patient to verify identity.\nPlease insert or update the image.", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {

                try {
                    firstName = firstNameTf.getText();
                    middleName = middleNameTf.getText();
                    lastName = lastNameTf.getText();

                    if (maleCbButton.isSelected()) {
                        genderSelect = "Male";
                    } else if (femaleCbButton.isSelected()) {
                        genderSelect = "Female";
                    }

                    dateOfBirth = dateOfBirthPicker.getDateStringOrEmptyString(); // bday
                    bloodType = String.valueOf(bloodTypeCB.getSelectedItem());
                    civilStatus = String.valueOf(civilStatusCB.getSelectedItem());
                    religion = String.valueOf(religionCB.getSelectedItem());
                    nationality = nationalityTf.getText();
                    cellphoneNumber = phoneNumberTf.getText();

                    if (verifyFields()) {
                        PreparedStatement pst;
                        String updatePatientQuery = "UPDATE `patients` SET `FirstName`=?,`MiddleName`=?,`LastName`=?,`Gender`=?,`DateOfBirth`=?,`BloodType`=?,`CivilStatus`=?,`Religion`=?,`Nationality`=?,`CellphoneNumber`=?,`ImagePath`=? WHERE id = " + patientIdTf.getText();

                        try {

                            pst = (PreparedStatement) HEALTH_MONITORING_SYSTEM_DATABASE.getConnection().prepareStatement(updatePatientQuery);
                            pst.setString(1, firstName);
                            pst.setString(2, middleName);
                            pst.setString(3, lastName);
                            pst.setString(4, genderSelect);
                            pst.setString(5, dateOfBirth);
                            pst.setString(6, bloodType);
                            pst.setString(7, civilStatus);
                            pst.setString(8, religion);
                            pst.setString(9, nationality);
                            pst.setString(10, cellphoneNumber);

                            try {
                                // Save the image as BLOB in the Database
                                if (image_path != null) {

                                    InputStream image = new FileInputStream(new File(image_path));
                                    pst.setBlob(11, image);
                                } else if (image_path == null) {
                                    pst.setNull(11, java.sql.Types.NULL);
                                    System.out.println("No image attached.");
                                } else {
                                    pst.setNull(1, java.sql.Types.NULL);
                                    System.out.println("No image attached.");
                                }
                                if (pst.executeUpdate() != 0) {
                                    JOptionPane.showMessageDialog(null, "Patient data has been updated.");
                                    clearAllInputFields();
                                    this.invalidate();
                                    this.validate();
                                    this.repaint();
                                    // Refresh patientDataTable after adding new entry to database
                                    dao.populatepatientDataTableFromMySQLDatabase(model, patientDataTable);
                                } else {
                                    JOptionPane.showMessageDialog(null, "Error: Check your Information.");
                                }
                                pst.setNull(11, java.sql.Types.NULL);
                            } catch (FileNotFoundException ex) {
                                JOptionPane.showMessageDialog(null, ex);
                            }
                        } catch (HeadlessException | SQLException ex) {
                            JOptionPane.showMessageDialog(null, ex);
                        }

                    }
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }


    }//GEN-LAST:event_updateButtonActionPerformed

    private void exportExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelButtonActionPerformed
        String currentDirectoryFilePathToExport = "C:\\Users\\Public\\Desktop";
        JFileChooser excelExportChooser = new JFileChooser(currentDirectoryFilePathToExport);
        // Filter only excel files
        FileNameExtensionFilter excelFNEF = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelExportChooser.setFileFilter(excelFNEF);
        // Set Dialogue Box Title
        excelExportChooser.setDialogTitle("Export Patient Database");
        int excelChooser = excelExportChooser.showSaveDialog(null);

        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            // Add Excel Library to ClassPath.
            XSSFWorkbook excelXSSFWorkBookExporter = new XSSFWorkbook();
            XSSFSheet excelSheet = excelXSSFWorkBookExporter.createSheet("Patient's Data");
            // Loop through JTable columns and rows

            for (int i = 0; i < model.getRowCount(); i++) {
                XSSFRow excelRow = excelSheet.createRow(i);
                for (int j = 0; j < model.getColumnCount(); j++) {
                    XSSFCell excelCell = excelRow.createCell(j);

                    excelCell.setCellValue(model.getValueAt(i, j).toString());
                }
            }
            // Create unique name by using existing excel file names and appending .xlsx

            FileOutputStream excelFIS;
            BufferedOutputStream excelBOS;
            try {
                excelFIS = new FileOutputStream(excelExportChooser.getSelectedFile() + ".xlsx");
                excelBOS = new BufferedOutputStream(excelFIS);
                excelXSSFWorkBookExporter.write(excelBOS);
                excelBOS.close();
                excelXSSFWorkBookExporter.close();
            } catch (IOException iOException) {
            }
            JOptionPane.showMessageDialog(null, "Exported data successfully.");
        }
    }//GEN-LAST:event_exportExcelButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            boolean printPatientTable = patientDataTable.print();

            if (!printPatientTable) {
            } else {
                JOptionPane.showMessageDialog(null, "Printed successfully.");
            }

        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void listSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSelectedButtonActionPerformed
        ListSelectedJTableRowsJFrame showListSelectedRows = new ListSelectedJTableRowsJFrame();

        int modelSelectedRow = patientDataTable.getSelectedRow();
        if (modelSelectedRow == -1) {
            JOptionPane.showMessageDialog(null, "No selected row in the list.", "Nothing selected", JOptionPane.INFORMATION_MESSAGE);
        } else {
            showListSelectedRows.setVisible(true);

            // Clear all rows before populating 
            showListSelectedRows.listSelectedJTableRowsJFrameModel.setRowCount(0);
            // Store selected rows in an integer array
            int[] getSelectedRows = patientDataTable.getSelectedRows();
            Object[] objects = new Object[11];

            for (int row = 0; row < getSelectedRows.length; row++) {
                objects[0] = model.getValueAt(getSelectedRows[row], 0);
                objects[1] = model.getValueAt(getSelectedRows[row], 1);
                objects[2] = model.getValueAt(getSelectedRows[row], 2);
                objects[3] = model.getValueAt(getSelectedRows[row], 3);
                objects[4] = model.getValueAt(getSelectedRows[row], 4);
                objects[5] = model.getValueAt(getSelectedRows[row], 5);
                objects[6] = model.getValueAt(getSelectedRows[row], 6);
                objects[7] = model.getValueAt(getSelectedRows[row], 7);
                objects[8] = model.getValueAt(getSelectedRows[row], 8);
                objects[9] = model.getValueAt(getSelectedRows[row], 9);
                objects[10] = model.getValueAt(getSelectedRows[row], 10);

                showListSelectedRows.listSelectedJTableRowsJFrameModel.addRow(objects);

            }

        }


    }//GEN-LAST:event_listSelectedButtonActionPerformed

    private void importExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importExcelButtonActionPerformed
        ImportDataFromExcel showImportDataFromExcelFrame = new ImportDataFromExcel();
        showImportDataFromExcelFrame.setVisible(true);
    }//GEN-LAST:event_importExcelButtonActionPerformed

    private void moveRowUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRowUpButtonActionPerformed

        // GetSelectedRow First and Store its value in a variable
        int getSelectedRow = patientDataTable.getSelectedRow();
        if (getSelectedRow > 0) {
            System.out.println(getSelectedRow);
            model.moveRow(getSelectedRow, getSelectedRow, getSelectedRow - 1);
            patientDataTable.getSelectionModel().setSelectionInterval(getSelectedRow - 1, getSelectedRow - 1);
        } else {
            JOptionPane.showMessageDialog(null, "You have reached the top row.");
        }
    }//GEN-LAST:event_moveRowUpButtonActionPerformed

    private void moveRowDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRowDownButtonActionPerformed
        int getSelectedRow = patientDataTable.getSelectedRow();
        if (getSelectedRow > 0) {
            model.moveRow(getSelectedRow, getSelectedRow, getSelectedRow + 1);
            patientDataTable.getSelectionModel().setSelectionInterval(getSelectedRow + 1, getSelectedRow + 1);
        } else {
            JOptionPane.showMessageDialog(null, "You have reached the bottom row.");
        }
    }//GEN-LAST:event_moveRowDownButtonActionPerformed

    private void patientDataTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientDataTableKeyReleased
        // Get the selected row index
        patientDataTableSelectedRow = patientDataTable.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            selectPatient(patientDataTableSelectedRow);
        }
    }//GEN-LAST:event_patientDataTableKeyReleased

    private void filterSearchTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterSearchTfKeyReleased
        String query = filterSearchTf.getText();
        filter(query);
    }//GEN-LAST:event_filterSearchTfKeyReleased

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException
                | InstantiationException
                | IllegalAccessException
                | UnsupportedLookAndFeelException e) {
            System.out.println(e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new HMS_PATIENT_MANAGEMENTSYSTEM().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(HMS_PATIENT_MANAGEMENTSYSTEM.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> bloodTypeCB;
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JButton browseImageButton;
    private javax.swing.JLabel cellphoneNumberLabel;
    private javax.swing.JComboBox<String> civilStatusCB;
    private javax.swing.JLabel civilStatusLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dateOfBirthLabel;
    private com.github.lgooddatepicker.components.DatePicker dateOfBirthPicker;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exportExcelButton;
    private javax.swing.JCheckBox femaleCbButton;
    private javax.swing.JTextField filterSearchTf;
    private javax.swing.JButton firstItemInListButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel imageNameLabel;
    private javax.swing.JTextField imageNameTf;
    private javax.swing.JLabel imagePathLabel;
    private javax.swing.JTextField imagePathTf;
    private javax.swing.JButton importExcelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JButton lastItemInListButton;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JButton listSelectedButton;
    private javax.swing.JCheckBox maleCbButton;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField middleNameTf;
    private javax.swing.JButton moveRowDownButton;
    private javax.swing.JButton moveRowUpButton;
    private javax.swing.JLabel nationalityLabel;
    private javax.swing.JTextField nationalityTf;
    private javax.swing.JButton nextItemInListButton;
    public static javax.swing.JTable patientDataTable;
    private javax.swing.JPanel patientFullMainPanel;
    private javax.swing.JLabel patientIDLabel;
    private javax.swing.JTextField patientIdTf;
    private javax.swing.JTextField phoneNumberTf;
    private javax.swing.JButton previousItemInListButton;
    private javax.swing.JButton printButton;
    private javax.swing.JComboBox<String> religionCB;
    private javax.swing.JLabel religionLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
