/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthMonitoringSystem;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;


/**
 *
 * @author Khian Orland
 */
public class HMS_EMPLOYEE_REGISTRATION extends javax.swing.JFrame {

    /**
     * Creates new form HMS_EMPLOYEE_REGISTRATION
     */
    
    
    public HMS_EMPLOYEE_REGISTRATION() {
        
        try { 
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | 
            InstantiationException | 
            IllegalAccessException | 
            UnsupportedLookAndFeelException e) {
        }
        
        initComponents();
        
        // create a button group for Gender
        ButtonGroup genderButtonGroup = new ButtonGroup();
        genderButtonGroup.add(maleButton);
        genderButtonGroup.add(femaleButton);
        
        Date dateNow = new Date();
        System.out.println(dateNow);
        
    }
    // limit phone number max
       public class JTextFieldLimit extends PlainDocument {
        private int limit;

        JTextFieldLimit(int limit) {
         super();
         this.limit = limit;
         }

        public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
          if (str == null) return;

          if ((getLength() + str.length()) <= limit) {
            super.insertString(offset, str, attr);
          }
        }
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        employeeRagistrationImageLabel = new javax.swing.JLabel();
        employeeRegistrationMainPanel = new javax.swing.JPanel();
        fullNameLabel = new javax.swing.JLabel();
        employeeFirstNameTf = new javax.swing.JTextField();
        employeeMiddleInitialTf = new javax.swing.JTextField();
        employeeLastNameTf = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        dateOfBirthLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeHomeAddressTA = new javax.swing.JTextArea();
        homeAddressLabel1 = new javax.swing.JLabel();
        birthdayPicker = new com.toedter.calendar.JDateChooser();
        employeePhoneNumberTf = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 241, 253));
        setMinimumSize(new java.awt.Dimension(1000, 621));
        setName("hmsEmployeeRegistrationFrame"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(235, 241, 253));

        employeeRagistrationImageLabel.setBackground(new java.awt.Color(235, 241, 253));
        employeeRagistrationImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthMonitoringSystem/APP_IMAGES/login_images/HMS_TOPPANEL_EMPLOYEE_REGISTER.png"))); // NOI18N

        employeeRegistrationMainPanel.setBackground(new java.awt.Color(235, 241, 253));

        fullNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        fullNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fullNameLabel.setText("Full Name:");

        employeeFirstNameTf.setBackground(new java.awt.Color(204, 204, 255));
        employeeFirstNameTf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        employeeFirstNameTf.setText("First Name");
        employeeFirstNameTf.setToolTipText("First name of the Employee");
        employeeFirstNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeFirstNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeeFirstNameTfFocusLost(evt);
            }
        });
        employeeFirstNameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeFirstNameTfKeyPressed(evt);
            }
        });

        employeeMiddleInitialTf.setBackground(new java.awt.Color(204, 204, 255));
        employeeMiddleInitialTf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        employeeMiddleInitialTf.setText("Middle Initial / Middle Name");
        employeeMiddleInitialTf.setToolTipText("Middle Initial or Complete Middle Name");
        employeeMiddleInitialTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeMiddleInitialTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeeMiddleInitialTfFocusLost(evt);
            }
        });
        employeeMiddleInitialTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeMiddleInitialTfKeyPressed(evt);
            }
        });

        employeeLastNameTf.setBackground(new java.awt.Color(204, 204, 255));
        employeeLastNameTf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        employeeLastNameTf.setText("Last Name");
        employeeLastNameTf.setToolTipText("Complete Last Name");
        employeeLastNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeLastNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeeLastNameTfFocusLost(evt);
            }
        });
        employeeLastNameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeLastNameTfKeyPressed(evt);
            }
        });

        genderLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderLabel.setText("Gender:");

        maleButton.setBackground(new java.awt.Color(235, 241, 253));
        maleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maleButton.setSelected(true);
        maleButton.setText("Male");

        femaleButton.setBackground(new java.awt.Color(235, 241, 253));
        femaleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        femaleButton.setText("Female");

        dateOfBirthLabel.setBackground(new java.awt.Color(255, 255, 255));
        dateOfBirthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateOfBirthLabel.setText("Birthday:");

        employeeHomeAddressTA.setBackground(new java.awt.Color(204, 204, 255));
        employeeHomeAddressTA.setColumns(20);
        employeeHomeAddressTA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        employeeHomeAddressTA.setLineWrap(true);
        employeeHomeAddressTA.setRows(5);
        employeeHomeAddressTA.setText("Complete Address of the Employee...");
        employeeHomeAddressTA.setToolTipText("Complete Address of the Employee...");
        employeeHomeAddressTA.setWrapStyleWord(true);
        employeeHomeAddressTA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeHomeAddressTAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeeHomeAddressTAFocusLost(evt);
            }
        });
        employeeHomeAddressTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeHomeAddressTAKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(employeeHomeAddressTA);

        homeAddressLabel1.setBackground(new java.awt.Color(255, 255, 255));
        homeAddressLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeAddressLabel1.setText("Home Address:");

        employeePhoneNumberTf.setBackground(new java.awt.Color(204, 204, 255));
        employeePhoneNumberTf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        employeePhoneNumberTf.setToolTipText("Please indicate your Phone number starting at 09xxxxxxxx");
        employeePhoneNumberTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeePhoneNumberTfKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeePhoneNumberTfKeyTyped(evt);
            }
        });
        employeePhoneNumberTf.setDocument(new JTextFieldLimit(11));

        phoneNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNumberLabel.setText("Phone Number (09xx):");

        javax.swing.GroupLayout employeeRegistrationMainPanelLayout = new javax.swing.GroupLayout(employeeRegistrationMainPanel);
        employeeRegistrationMainPanel.setLayout(employeeRegistrationMainPanelLayout);
        employeeRegistrationMainPanelLayout.setHorizontalGroup(
            employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeRegistrationMainPanelLayout.createSequentialGroup()
                .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeeRegistrationMainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(homeAddressLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeeRegistrationMainPanelLayout.createSequentialGroup()
                        .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(employeeRegistrationMainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePhoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateOfBirthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(birthdayPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeeRegistrationMainPanelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(fullNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeMiddleInitialTf, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeeRegistrationMainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeLastNameTf))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeRegistrationMainPanelLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(genderLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maleButton)
                                .addGap(12, 12, 12)
                                .addComponent(femaleButton)))))
                .addGap(20, 20, 20))
        );
        employeeRegistrationMainPanelLayout.setVerticalGroup(
            employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeRegistrationMainPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeMiddleInitialTf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeRegistrationMainPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maleButton)
                            .addComponent(femaleButton))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeRegistrationMainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeRegistrationMainPanelLayout.createSequentialGroup()
                                .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phoneNumberLabel)
                                .addComponent(employeePhoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(birthdayPicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(employeeRegistrationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeAddressLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addGroup(employeeRegistrationMainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(357, 357, 357))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeRagistrationImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeRegistrationMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(employeeRagistrationImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeRegistrationMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 667);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void employeeMiddleInitialTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeMiddleInitialTfFocusLost
         if (employeeMiddleInitialTf.getText().trim().equals("")) // placeholder
        {
            employeeMiddleInitialTf.setText("Middle Initial / Middle Name");
            employeeMiddleInitialTf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_employeeMiddleInitialTfFocusLost

    private void employeeMiddleInitialTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeMiddleInitialTfKeyPressed
           if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeeMiddleInitialTfKeyPressed

    private void employeeMiddleInitialTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeMiddleInitialTfFocusGained
         if (employeeMiddleInitialTf.getText().trim().equals("Middle Initial / Middle Name"))
        {
            employeeMiddleInitialTf.setText("");
            employeeMiddleInitialTf.setForeground(Color.black);
        }
    }//GEN-LAST:event_employeeMiddleInitialTfFocusGained

    private void employeeLastNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeLastNameTfFocusGained
        if (employeeLastNameTf.getText().trim().equals("") ||
           (employeeLastNameTf.getText().trim().equals("Last Name")))
        {
            employeeLastNameTf.setText("");
            employeeLastNameTf.setForeground(Color.black);
        }
    }//GEN-LAST:event_employeeLastNameTfFocusGained

    private void employeeLastNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeLastNameTfFocusLost
        if (employeeLastNameTf.getText().trim().equals("")) // placeholder
        {
            employeeLastNameTf.setText("Last Name");
            employeeLastNameTf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_employeeLastNameTfFocusLost

    private void employeeLastNameTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeLastNameTfKeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeeLastNameTfKeyPressed

    private void employeeFirstNameTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeFirstNameTfKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeeFirstNameTfKeyPressed

    private void employeeFirstNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeFirstNameTfFocusLost
        if (employeeFirstNameTf.getText().trim().equals("")) // placeholder
        {
            employeeFirstNameTf.setText("First Name");
            employeeFirstNameTf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_employeeFirstNameTfFocusLost

    private void employeeFirstNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeFirstNameTfFocusGained
        if (employeeFirstNameTf.getText().trim().equals("First Name") ||
           (employeeFirstNameTf.getText().trim().equals("")))
        {
            employeeFirstNameTf.setText("");
            employeeFirstNameTf.setForeground(Color.black);
        }
    }//GEN-LAST:event_employeeFirstNameTfFocusGained

    private void employeeHomeAddressTAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeHomeAddressTAKeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeeHomeAddressTAKeyPressed

    private void employeeHomeAddressTAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeHomeAddressTAFocusGained
        if (employeeHomeAddressTA.getText().trim().equals("Complete Address of the Employee...") ||
           (employeeHomeAddressTA.getText().trim().equals("")))
        {
            employeeHomeAddressTA.setText("");
            employeeHomeAddressTA.setForeground(Color.black);
        }
    }//GEN-LAST:event_employeeHomeAddressTAFocusGained

    private void employeeHomeAddressTAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeHomeAddressTAFocusLost
        if (employeeHomeAddressTA.getText().trim().equals("")) // placeholder
        {
            employeeHomeAddressTA.setText("Complete Address of the Employee...");
            employeeHomeAddressTA.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_employeeHomeAddressTAFocusLost

    private void employeePhoneNumberTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeePhoneNumberTfKeyTyped
        // allow only numbers
        if (!Character.isDigit(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_employeePhoneNumberTfKeyTyped

    private void employeePhoneNumberTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeePhoneNumberTfKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_employeePhoneNumberTfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMS_EMPLOYEE_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMS_EMPLOYEE_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMS_EMPLOYEE_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMS_EMPLOYEE_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMS_EMPLOYEE_REGISTRATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birthdayPicker;
    public javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JTextField employeeFirstNameTf;
    private javax.swing.JTextArea employeeHomeAddressTA;
    private javax.swing.JTextField employeeLastNameTf;
    private javax.swing.JTextField employeeMiddleInitialTf;
    private javax.swing.JTextField employeePhoneNumberTf;
    private javax.swing.JLabel employeeRagistrationImageLabel;
    private javax.swing.JPanel employeeRegistrationMainPanel;
    private javax.swing.JRadioButton femaleButton;
    public javax.swing.JLabel fullNameLabel;
    public javax.swing.JLabel genderLabel;
    public javax.swing.JLabel homeAddressLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel phoneNumberLabel;
    // End of variables declaration//GEN-END:variables
}
